Updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -66,9 +66,19 @@ commands:
       - run:
           name: Export TARGET_WORKFLOW
           command: |
-            echo "export TARGET_WORKFLOW=${CIRCLE_WORKFLOW_ID:-$CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
+            echo "export TARGET_BRANCH=${CIRCLE_BRANCH}" >> $BASH_ENV
+            source $BASH_ENV
 
-            cat $BASH_ENV
+            ./scripts/find-branch-workflow.sh > workflow
+
+            TARGET_WORKFLOW=$(cat workflow | tr -d '\n')
+
+            if [ -z "$TARGET_WORKFLOW" ]; then
+              echo "ERROR: No workflow found for branch ${TARGET_BRANCH}"
+              exit 1
+            fi
+
+            echo "export TARGET_WORKFLOW=${TARGET_WORKFLOW}" >> $BASH_ENV
 
             source $BASH_ENV
 
