fixing package cloud

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -271,7 +271,10 @@ commands:
             baseURL="https://github.com/amdprophet/packagecloud-go/releases/download"
             version="0.1.2"
             file="packagecloud-go_${version}_linux_amd64.tar.gz"
-            curl -fL -o /tmp/packagecloud-go.tar.gz $baseURL/$version/$file
+            if ! curl -fL -o /tmp/packagecloud-go.tar.gz $baseURL/$version/$file; then
+              echo "Error downloading packagecloud-go: $?"
+            fi
+            echo "Packagecloud-go downloaded successfully!"
       - run:
           name: Install packagecloud-go tool
           command: |
